# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

environment:
  NOT_CRAN: true
  # env vars that may need to be set, at least temporarily, from time to time
  # see https://github.com/krlmlr/r-appveyor#readme for details
  # USE_RTOOLS: true
  R_REMOTES_STANDALONE: true
  TEXLIVE_PREFER_OWN: 1

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps
  - cmd: Rscript -e "tinytex::install_tinytex()"
  - cmd: Rscript -e "tinytex::tlmgr_install('latexdiff')"
  - cmd: Rscript -e "tinytex::tlmgr_path('add')"
  - set PATH=%APPDATA%\TinyTex\bin\win32;%PATH%
  - echo %PATH%
  - dir %APPDATA%\TinyTex
  - dir %APPDATA%\TinyTex\bin'win32
  - dir %APPDATA%\TinyTex\texmf-dist\tex
  - dir %APPDATA%\TinyTex\texmf-dist\tex\latex\la*

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
