# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # - {os: macos-latest,   r: 'release'}
          # - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          # - {os: ubuntu-latest,   r: 'release'}
          # - {os: ubuntu-latest,   r: 'oldrel-1'}
          - {os: windows-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - name: Install Algorithm::Diff
        if: runner.os == 'Windows'
        uses: perl-actions/install-with-cpm@stable
        with:
          install: "Algorithm::Diff"

      - name: Install latexdiff
        shell: bash
        run: |
          curl -L -s https://mirrors.ctan.org/support/latexdiff.zip -o latexdiff.zip
          unzip latexdiff.zip
          # cd latexdiff
          mkdir -p "${RUNNER_TEMP}/latexdiff"
          cp -R latexdiff/* "${RUNNER_TEMP}/latexdiff/"
          echo "${RUNNER_TEMP}/latexdiff/" >> $GITHUB_PATH
          # sudo make install
          # cd ..
          rm -rf latexdiff
          "${RUNNER_TEMP}/latexdiff/latexdiff" --version

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
